### ISSUE TITLE
Detect and prettify links in publication_details field

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/thomas-bernhard-in-translation#26]
Two Georgian translations from 2008 feature oddly formatted non-interactive URLs in their "published by" sections:
https://thomas-bernhard-translation.acdh.oeaw.ac.at/de/publications/591
https://thomas-bernhard-translation.acdh.oeaw.ac.at/de/publications/592

These should be removed.

---

Note: the doc from which I'm transcribing these issues contains a comment which says they've already been removed from the backend, which idk how to interpret since I'm still seeing them on the pages linked above. -> Somebody more knowledgeable about the inner workings of the app will have to decide if/when to mark this issue as obsolete.

**Comment by ctot-nondef** [comment]
was corrected in data as far as I can see / probably just needs to be republished to typesense @kevinstadler

**Comment by kevinstadler** [comment]
Links are still present in the `publication_details` column of the current state of Baserow -- probably the best thing would be to auto-detect URLs and prettify/make them clickable in the frontend, e.g. by running the `publication_details` field through a Markdown formatter, around here:
https://github.com/acdh-oeaw/thomas-bernhard-in-translation/blob/0aa0c774a34204380ade522bd952499603595ec0/app/%5Blocale%5D/publications/%5Bid%5D/page.tsx#L107
